kommitters/soroban.ex

- config/config.exs
- config/dev.exs
- config/prod.exs
- config/test.exs
- mix.exs
Add config files to allow the `hexdocs`  publish
> Add config files

- lib/rpc/error.ex
- test/rpc/error_test.exs
> RPC error type

- CHANGELOG.md
- mix.exs
> Prepare release v0.2.0

- CHANGELOG.md
- README.md
- mix.exs
> Prepare release v0.3.0

- lib/rpc/endpoints/simulate_transaction.ex
- lib/rpc/endpoints/spec.ex
- test/rpc/endpoints/simulate_transaction_test.exs
> SimulateTransaction request

- lib/rpc/endpoints/send_transaction.ex
- lib/rpc/rpc.ex
- test/rpc/endpoints/send_transaction_test.exs
- test/rpc/rpc_test.exs
> SendTransaction request

- README.md
- lib/rpc/client/spec.ex
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Closes #16
Please delete options that are not relevant.
> RPC README docs

- CHANGELOG.md
- README.md
- mix.exs
> Prepare release v0.4.0

- lib/types/enum.ex
- lib/types/map.ex
- lib/types/map_entry.ex
- lib/types/option.ex
- lib/types/spec.ex
- lib/types/struct.ex
- lib/types/struct_field.ex
- lib/types/tuple.ex
- lib/types/vec.ex
- test/types/enum_test.exs
- test/types/map_entry_test.exs
- test/types/map_test.exs
- test/types/option_test.exs
- test/types/struct_field_test.exs
- test/types/struct_test.exs
- test/types/tuple_test.exs
- test/types/vec_test.exs
> Soroban Compound Types

- lib/contract.ex
- lib/contract/deploy_contract.ex
- test/contract/deploy_contract_test.exs
- test/contract_test.exs
> Deploy contract

- README.md
- lib/rpc.ex
- lib/rpc/endpoints/get_health.ex
- lib/rpc/responses/get_health_response.ex
- test/rpc/endpoints/get_health_test.exs
- test/rpc/responses/get_health_response_test.exs
- test/rpc_test.exs
> GetHealth request

- README.md
- lib/rpc.ex
- lib/rpc/endpoints/get_ledger_entry.ex
- lib/rpc/responses/get_ledger_entry_response.ex
- lib/rpc/responses/simulate_transaction_response.ex
- test/rpc/endpoints/get_ledger_entry_test.exs
- test/rpc/responses/get_ledger_entry_response_test.exs
- test/rpc_test.exs
> GetLedgerEntry request

- README.md
- lib/contract.ex
- lib/contract/install_contract_code.ex
- test/contract/install_contract_code_test.exs
- test/contract_test.exs
> InstallContractCode retrieve xdr to sign

- README.md
- lib/contract.ex
- lib/contract/deploy_contract.ex
- test/contract/deploy_contract_test.exs
- test/contract_test.exs
> DeployContract retrieve xdr to sign

- README.md
- lib/contract.ex
- lib/contract/invoke_contract_function.ex
- lib/contract/rpc_calls.ex
- test/contract/invoke_contract_function_test.exs
- test/contract_test.exs
> Update invoke function args

- README.md
> Update Contract Module documentation

- README.md
- lib/contract.ex
- lib/contract/deploy_asset_contract.ex
- test/contract/deploy_asset_contract_test.exs
- test/contract_test.exs
Fixes #136 
Please delete options that are not relevant.
> Allow invoker to be different from asset issuer

- .github/workflows/scorecards.yml
- CHANGELOG.md
- README.md
- mix.exs
> Prepare for release v0.18.0

- CHANGELOG.md
- README.md
- SECURITY.md
- mix.exs
Prepare release v0.20.0 and update SECURITY.md.
> Prepare release v0.20.0 and update SECURITY.md

- CHANGELOG.md
- README.md
- mix.exs
> Prepare release v0.20.1

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- mix.exs
- Add stale issues policy. See [PR #154](https://github.com/kommitters/soroban.ex/pull/154)
> Release v0.20.1

- README.md
- lib/rpc/responses/simulate_transaction_response.ex
The state_changes property was added in the SimulateTransactionResponse.
> Add state_changes in Simulate Transaction response

- CHANGELOG.md
- README.md
- mix.exs
> Add update for response in the endpoint gethealth

- CHANGELOG.md
- README.md
- lib/rpc/responses/get_health_response.ex
- mix.exs
- test/rpc/responses/get_health_response_test.exs
- test/rpc_test.exs
Update the getHealth endpoint response
Please delete options that are not relevant.
> Release v0.22
